##################################################################################
#
# Bänger by Marcin Orlowski
# Because your `banner` deserves to be a `bänger`!
#
# @author    Marcin Orlowski <mail@marcinOrlowski.com>
# Copyright  ©2025 Marcin Orlowski <MarcinOrlowski.com>
# @link      https://github.com/MarcinOrlowski/banger
#
##################################################################################

name: "Code lint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  unittests:
    name: "Linting"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout sources"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: "Look for changed files..."
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            srcs:
              - '**/*.py'

      - name: "Installing dependencies..."
        if: steps.filter.outputs.srcs == 'true'
        run: |
          pip install -e ".[dev]"

      - name: "Linting..."
        if: steps.filter.outputs.srcs == 'true'
        run: |
          flake8 --config .flake8.dist src/ tests/
